Lingering bringup repository in package xml
This line was causing the following error. It is residual from the recent changes. 

  kscottz@woodrat:~/turtlebot4_ws$ rosdep install --from-path src -yi
  ERROR: the following packages/stacks could not have their rosdep keys resolved
  to system dependencies:
  turtlebot4_ignition_bringup: Cannot locate rosdep definition for [turtlebot4_bringup]